[package]
name = "sql-adaptor"
version = "0.1.0"
edition = "2024"

[dependencies]
migration = { path = "migration/" }

async-std = { version = "1", features = ["attributes", "tokio1"] }
async-trait = "0.1.89"
chrono = "0.4.44"
common = { path = "../../common" }
sea-orm = { version = "1.1.20", features = [
  "macros",
  "runtime-tokio-rustls",
  "sqlx-mysql",
  "sqlx-postgres",
  "sqlx-sqlite",
] }
sea-orm-migration = "1.1.20"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
strum = { version = "0.28.0", features = ["derive"] }
tracing = "0.1.44"
