[tools]
"cargo:sea-orm-cli" = { version = "1.1.20", features = "sqlx-postgres" }
node = "24"

[tasks.generate-entities]
alias = "ge"
run = "sea generate entity --output-dir src/entity/ --with-prelude none"
dir = "{{ config_root }}/api/adaptors/sql"

[tasks.migrate]
alias = "m"
run = "sea migrate"
dir = "{{ config_root }}/api/adaptors/sql"

[tasks.run-api]
alias = "ra"
run = "cargo run"
dir = "{{ config_root }}/api"

[tasks.dev-api]
alias = "da"
run = "mise watch -fr run-api"
dir = "{{ config_root }}/api"
