[tools]
"cargo:sea-orm-cli" = { version = "1.1.20", features = "sqlx-postgres" }
node = "24"

[tasks.generate-entities]
alias = "ge"
run = "sea generate entity --output-dir src/entity/ --with-prelude none --compact-format"
dir = "{{ config_root }}/api/adaptors/sql"

[tasks.migrate]
alias = "m"
run = "sea migrate"
dir = "{{ config_root }}/api/adaptors/sql"

[tasks.generate-openapi]
alias = "go"
run = "yarn generate-openapi"
dir = "{{ config_root }}/frontend"

[tasks.run-api]
alias = "ra"
run = "cargo run"
dir = "{{ config_root }}/api"

[tasks.dev-api]
alias = "da"
run = "mise watch -fr run-api -w src -w adaptors -w common -w Cargo.toml -w Cargo.lock"
dir = "{{ config_root }}/api"

[tasks.dev-frontend]
alias = "df"
run = "yarn dev"
dir = "{{ config_root }}/frontend"

[tasks.dev]
depends = [{ task = "dev-frontend" }, { task = "dev-api" }]
