name: API Checks

on:
  pull_request:
    paths:
      - api/**
      - .github/workflows/check_api.yml
  push:
    branches:
      - main
    paths:
      - api/**
      - .github/workflows/check_api.yml

# Fail on warnings
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - command: clippy --workspace --all-targets --all-features
            component: clippy
            title: Clippy
          - command: fmt -- --check
            component: rustfmt
            title: Formatting

    name: ${{ matrix.title }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v6
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: ${{ matrix.component }}
          cache-shared-key: ${{ matrix.component }}
          cache-workspace-key: api -> target
      - run: cargo ${{ matrix.command }}
