name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container:
    name: Container
    uses: ./.github/workflows/build_container.yml
    permissions:
      contents: write
      id-token: write
      packages: write
